### ISSUE TITLE
Standardize relative frequencies for corpus and document terms

### ISSUE THREAD

**Issue by ajmacdonald** [voyanttools/trombone#26]
For document terms, relative frequencies get multiplied by 1 million at the server level: https://github.com/voyanttools/trombone/blob/5909345824051306f9ae6869baade224f40c772b/src/main/java/org/voyanttools/trombone/model/DocumentTerm.java#L86

For corpus terms, this happens at the client level: https://github.com/voyanttools/trombone/blob/5909345824051306f9ae6869baade224f40c772b/src/main/java/org/voyanttools/trombone/model/CorpusTerm.java#L126
and
https://github.com/voyanttools/Voyant/blob/ca2f7ed3fe05080d12b362e29457c49b61e287f2/src/main/webapp/app/panel/CorpusTerms.js#L165

**Comment by recrm** [comment]
Note, due to the fact that nearly all statistical calculations that use relative frequency assumes a number normalized as a percentage. My vote would be that the backend doesn't multiply by a million and that functionality be moved to the frontend exclusively.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/trombone/commit/be4eed4a6f471cbed1f748ffd86a15ecf6e890fe

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/af3de89e4e26f1bee3bdc893d3ddc2aede611ecd
