### ISSUE TITLE
Document Terms drops documents when run with minRawFreq and withDistributions.

### ISSUE THREAD

**Issue by recrm** [voyanttools/trombone#38]
![image](https://github.com/voyanttools/trombone/assets/1725327/a35273a0-5834-4014-b365-0286d91e0bb9)

When document terms is run with these two arguments passed to them the numbers change and some terms seem to fall out of documents.

**Comment by ajmacdonald** [comment]
There's an inconsistency in how `minRawFreq` is used.
If `withDistributions` is included, then `minRawFreq` is compared against the per document raw frequency. In the test example, the raw frequencies for the first two documents are below 3000, so the result isn't included.
If `withDistributions` isn't included, then `minRawFreq` is compared against corpus raw frequency.

I'm not sure what the best way to resolve this inconsistency is.

**Comment by recrm** [comment]
From the user perspective it is rather confusing that "withDistributions" modifies how the numbers are calulated, as it feels like it is just adding additional fields that are not there by default. My vote would be that the "minRawFreq" just acts as a filter on the output. So all values are calculated first, and then minRawFreq just filters which values are returned to the user.
