### ISSUE TITLE
minRawFreq appears to do nothing when used in correlations.

### ISSUE THREAD

**Issue by recrm** [voyanttools/trombone#40]
In the docs, minRawFreq appears as a valid argument for correlations. It appears to do nothing.

**Comment by ajmacdonald** [comment]
It was erroneously added to the docs and has been removed
https://github.com/voyanttools/voyantjs/commit/e624d5eacc98cfd8876c642cddf053641afb0d6e

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/ac9de04400ee2669921740a2751161fb93aabe71
